version: '3.8'
services:
  mongodb:
    image: mongo:8.0
    volumes:
      - ./storage/mongodb:/data/db:z
  redis:
    image: redis:7.4-alpine
    volumes:
      - ./storage/redis:/data:z
  hpfeeds3:
    image: stingar/hpfeeds3:1.9
    links:
      - mongodb:mongodb
    ports:
      - "10000:10000"
  mnemosyne:
    image: stingar/mnemosyne:1.9
    links:
      - mongodb:mongodb
      - hpfeeds3:hpfeeds3
  chnserver:
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - ./config/collector:/etc/collector:z
      - ./storage/chnserver/sqlite:/opt/sqlite:z
      - ./certs:/tls:z
    links:
      - mongodb:mongodb
      - redis:redis
      - hpfeeds3:hpfeeds3
    ports:
      - "80:80"
      - "443:443"
